name: Create Calling Widget Sample Release

on:
  release:
    types: [created]
    name: Release  

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build
        shell: bash
        run: |
          release_name=Calling-widget
          unset CI
          # Build everything
          npm run setup
          npm run build
          npm run package

          7z a -tzip -r "calling-widget.zip" ./app/dist/*

          # Delete output directory
          # rm -r "./app/dist"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "calling-widget.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
